name: Build & Push Docker Images

on:
  push:
    branches:
      - Elakkia 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Backend
      run: |
        docker build -t elakkiakarunakaran/ds-backend:latest ./backend
        docker push elakkiakarunakaran/ds-backend:latest

    - name: Build & Push Frontend
      run: |
        docker build -t elakkiakarunakaran/ds-frontend:latest ./frontend
        docker push elakkiakarunakaran/ds-frontend:latest

    - name: Build & Push NGINX
      run: |
        docker build -t elakkiakarunakaran/ds-nginx:latest ./nginx
        docker push elakkiakarunakaran/ds-nginx:latest
